### ISSUE TITLE
Paper tasks

### ISSUE THREAD

**Issue by natesheehan** [Digital-Water-Publics/ei_catchment_explorer#1]
### Todo for AAG paper

- [ ] Mine additional tweets until present
- [ ] Frequency analysis of nouns, adjectives, noun phrases
- [ ] Sentiment analysis with EmoLex
- [ ] Select tweets scoring above average on disgust
- [ ] Of this selection, generate a random sample of 1k-2k tweets
- [ ] Export sample as CSV
- [ ] Frequency analysis of nouns, adjectives, noun phrases
- [ ] List of top 10 trigger words for disgust
- [ ] Clean repo
- [ ] Check for error: the plot „emotion words expressed in tweets…“ plots only 7 of 8 emotions, sadness is missing. Generate this plot again for the complete corpus(https://trello.com/1/cards/6108fdb30b25f485d777befc/attachments/610910c7fa3d854ef468f4e7/download/image.png)
